### ISSUE TITLE
Is skookum.chat dead dead?

### ISSUE THREAD

**Issue by namrog84** [EpicSkookumScript/SkookumScript-Plugin#49]
I know skookumscript is mostly deprecrated/unmaintained at this point since it got acquired and they mostly work on Verse.
But I thought I had seen that there was some mention on the skookum.chat that there might be eventual interest in keeping it going in parallel with verse, maybe by the community.

But the chats have been down for a while now. 

Is it dead dead, or can the skookum.chat be brought up?

I know this isn't the right place but didn't know where else to ask/post.

**Comment by error454** [comment]
There has been interest expressed on all sides, the missing elements are time and motivation. Keeping the language working with all the changes to the engine is a monumental task that needs more skilled contributors. I'm guessing skookum.chat is just a DNS issue, I'll ping the maintainer.

**Comment by namrog84** [comment]
Not knowing how verse will be fully implemented when it comes to vanilla UE. I always assumed when it did, it'd be easier to potentially bind other 'scripting languages' to it and there'd be an explosion of transpilers/interpreters by various people.  And 1 of those things might be getting a skookumscript connected to the Verse VM/API somehow.  

So, I still had interest in it. I'm excited for Verse but was considering tackling something sooner, since it feels like that's years away, either skookumscript or angelscript or something.  I had seen NimForUE recently and saw they managed to get some functionality working without engine modification.

I was contemplating to take a stab at doing a NimForUE/Skookum-Lite hybrid approach.

**Comment by error454** [comment]
Well it looks like skookum.chat is officially dead, I was told there were some issues and backups were officially lost.

> I always assumed when it did, it'd be easier to potentially bind other 'scripting languages' to it and there'd be an explosion of transpilers/interpreters by various people.

There's always hoping, but none of that code has hit UE yet. The past/current integration is based on a lot of wild guesses and reverse engineering since there really aren't best practices for getting all the reflection stuff generated.

I have heard many good things about angelscript and it seems well supported. I think they took a very different hands-on approach with their bindings instead of going the reflection UHT route. This seems much easier to maintain, but that said this is only what I've heard, I've never used it.

> I had seen NimForUE recently and saw they managed to get some functionality working without engine modification.

Just as a clarifying point, SkookumScript worked fine without modifying the engine, until you went to package and publish and then odd issues came up at runtime on certain platforms because of the difference in the initialization order of the engine. It was those edge cases that I *felt* necessitated the engine changes.

Some other scripting solutions may have this same fate, but since most projects never ship, (and if they do, only on PC), they never see the issues.
